# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstation.proto\"O\n\x12RecordTempsRequest\x12\x0f\n\x07station\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04tmin\x18\x03 \x01(\x05\x12\x0c\n\x04tmax\x18\x04 \x01(\x05\"!\n\x10RecordTempsReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"$\n\x11StationMaxRequest\x12\x0f\n\x07station\x18\x01 \x01(\t\".\n\x0fStationMaxReply\x12\x0c\n\x04tmax\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t2x\n\x07Station\x12\x37\n\x0bRecordTemps\x12\x13.RecordTempsRequest\x1a\x11.RecordTempsReply\"\x00\x12\x34\n\nStationMax\x12\x12.StationMaxRequest\x1a\x10.StationMaxReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'station_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RECORDTEMPSREQUEST']._serialized_start=17
  _globals['_RECORDTEMPSREQUEST']._serialized_end=96
  _globals['_RECORDTEMPSREPLY']._serialized_start=98
  _globals['_RECORDTEMPSREPLY']._serialized_end=131
  _globals['_STATIONMAXREQUEST']._serialized_start=133
  _globals['_STATIONMAXREQUEST']._serialized_end=169
  _globals['_STATIONMAXREPLY']._serialized_start=171
  _globals['_STATIONMAXREPLY']._serialized_end=217
  _globals['_STATION']._serialized_start=219
  _globals['_STATION']._serialized_end=339
# @@protoc_insertion_point(module_scope)
