# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmath.proto\"\x1f\n\x07MultReq\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1b\n\x0bMultManyReq\x12\x0c\n\x04nums\x18\x01 \x03(\x05\"\x1a\n\x08MultResp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32H\n\x04\x43\x61lc\x12\x1b\n\x04Mult\x12\x08.MultReq\x1a\t.MultResp\x12#\n\x08MultMany\x12\x0c.MultManyReq\x1a\t.MultRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'math_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MULTREQ']._serialized_start=14
  _globals['_MULTREQ']._serialized_end=45
  _globals['_MULTMANYREQ']._serialized_start=47
  _globals['_MULTMANYREQ']._serialized_end=74
  _globals['_MULTRESP']._serialized_start=76
  _globals['_MULTRESP']._serialized_end=102
  _globals['_CALC']._serialized_start=104
  _globals['_CALC']._serialized_end=176
# @@protoc_insertion_point(module_scope)
