# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import station_pb2 as station__pb2


class StationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordTemps = channel.unary_unary(
                '/Station/RecordTemps',
                request_serializer=station__pb2.RecordTempsRequest.SerializeToString,
                response_deserializer=station__pb2.RecordTempsReply.FromString,
                )
        self.StationMax = channel.unary_unary(
                '/Station/StationMax',
                request_serializer=station__pb2.StationMaxRequest.SerializeToString,
                response_deserializer=station__pb2.StationMaxReply.FromString,
                )


class StationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordTemps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StationMax(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordTemps': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTemps,
                    request_deserializer=station__pb2.RecordTempsRequest.FromString,
                    response_serializer=station__pb2.RecordTempsReply.SerializeToString,
            ),
            'StationMax': grpc.unary_unary_rpc_method_handler(
                    servicer.StationMax,
                    request_deserializer=station__pb2.StationMaxRequest.FromString,
                    response_serializer=station__pb2.StationMaxReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Station', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Station(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordTemps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Station/RecordTemps',
            station__pb2.RecordTempsRequest.SerializeToString,
            station__pb2.RecordTempsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StationMax(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Station/StationMax',
            station__pb2.StationMaxRequest.SerializeToString,
            station__pb2.StationMaxReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
